In [71]:
import numpy as np
import random
import pandas as pd
import sys
sys.path.append('../')
from assesssample import AssessVarQuant, AssessVarCat, AssessCombVar
from variablesampling import SampleVarCat, SampleVarQuant

## Multiple var cat

In [2]:
a = [[1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [1,0,0,0],
    [0,0,1,0],
    [0,1,0,0],
    [0,1,0,0],
    [0,0,0,1]]

In [4]:
a = np.array(a)

In [11]:
freqs = a.sum(axis=0)/len(a)
freqs

array([0.25 , 0.375, 0.25 , 0.125])

In [60]:
# for a sample of 4
n_samples = 4
counts_sample = n_samples * freqs

In [61]:
counts_sample = counts_sample.astype(int)

In [62]:
y = np.where(counts_sample.astype(int) == 1)[0]
y

array([0, 1, 2], dtype=int64)

In [63]:
x = np.where(a[:,y[2]] == 1)[0]

In [64]:
np.random.choice(x)

4

In [68]:
sample_idx = []
for y in np.where(counts_sample.astype(int) == 1)[0]:
    x = np.where(a[:,y] == 1)[0]
    sample_idx.extend(np.random.choice( x , size= counts_sample[y] ,replace=False).tolist())
while (len(sample_idx) < n_samples):
    idx = range(len(a))
    x = random.choice(idx)
    if x not in sample_idx:
        sample_idx.append(x)

In [69]:
sample_idx

[3, 6, 2, 5]

In [70]:
a[sample_idx,:]

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0]])

In [72]:
AssessVarCat(a[sample_idx,0], a[:,0]).evaluate()

1.0

In [73]:
pvals = [AssessVarCat(a[sample_idx,i], a[:,i]).evaluate() for i in range(a.shape[1])]

I:\Data_repr\venv\lib\site-packages\scipy\stats\stats.py:4567: RuntimeWarning: invalid value encountered in true_divide
  terms = (f_obs - f_exp)**2 / f_exp
I:\Data_repr\venv\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
I:\Data_repr\venv\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
I:\Data_repr\venv\lib\site-packages\scipy\stats\_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)


In [74]:
pvals

[1.0, 1.0, 1.0, nan]